# This chart was originally developed by @MAVRICK-1
# Source: https://github.com/MAVRICK-1/kubestellar-ui

apiVersion: v2
name: kubestellar-ui
description: A Helm chart for kubestellar UI on Kubernetes
type: application
version: "0.1.0"
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/kubestellar/ui/refs/heads/dev/public/logo.svg

dependencies:
  - name: redis
    version: "21.2.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
