version: 2
updates:
  - package-ecosystem: "npm"  
    directory: "/"             
    schedule:
      interval: "weekly"       
    versioning-strategy: "increase"
  - package-ecosystem: "gomod"  
    directory: "/backend"            
    schedule:
      interval: "weekly"     
    versioning-strategy: "increase"
