presubmits:
  - name: pull-kubestellar-ui-verify
    always_run: true
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              cd frontend
              npm ci
              npm run lint
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi
  - name: pull-kubestellar-ui-build
    always_run: true
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              cd frontend
              rm -rf ~/.npm ~/.cache node_modules
              npm ci
              npm run build
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi
  - name: pull-kubestellar-ui-test
    always_run: true
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: node:20
          command:
            - /bin/bash
            - -c
            - |
              cd frontend
              rm -rf ~/.npm ~/.cache node_modules
              npm ci
              npm test
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi
  - name: pull-kubestellar-ui-backend-verify
    always_run: true
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: golang:1.24
          command:
            - /bin/bash
            - -c
            - |
              cd backend
              go mod download
              go vet ./...
          resources:
            requests:
              memory: 1Gi
              cpu: 1
              ephemeral-storage: 4Gi
  - name: pull-kubestellar-ui-backend-test
    always_run: true
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: golang:1.24
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y redis-server redis-tools
              redis-server --daemonize yes --port 6379 --bind 127.0.0.1 --save "" --appendonly no
              echo "Waiting for Redis to start..."
              sleep 3

              if redis-cli ping | grep -q PONG; then
                echo "✓ Redis is running"
              else
                echo "✗ Redis failed to start"
                exit 1
              fi

              cd backend
              go mod download
              go test ./...
          resources:
            requests:
              memory: 1Gi
              cpu: 1
              ephemeral-storage: 4Gi

postsubmits:
  - name: post-kubestellar-ui-build-main
    branches:
      - ^main$
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: quay.io/buildah/stable:latest
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              # Build and push frontend
              cd frontend
              buildah bud -t quay.io/kubestellar/ui:frontend-$(git rev-parse --short HEAD) -t quay.io/kubestellar/ui:frontend-latest .
              buildah push quay.io/kubestellar/ui:frontend-$(git rev-parse --short HEAD)
              buildah push quay.io/kubestellar/ui:frontend-latest
              cd ..

              # Build and push backend
              cd backend
              buildah bud -t quay.io/kubestellar/ui:backend-$(git rev-parse --short HEAD) -t quay.io/kubestellar/ui:backend-latest .
              buildah push quay.io/kubestellar/ui:backend-$(git rev-parse --short HEAD)
              buildah push quay.io/kubestellar/ui:backend-latest
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi

  - name: post-kubestellar-ui-build-dev
    branches:
      - ^dev$
    decorate: true
    clone_uri: 'https://github.com/kubestellar/ui'
    spec:
      containers:
        - image: quay.io/buildah/stable:latest
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              # Build and push frontend
              cd frontend
              buildah bud -t quay.io/kubestellar/ui:frontend-dev-$(git rev-parse --short HEAD) -t quay.io/kubestellar/ui:frontend-dev-latest .
              buildah push quay.io/kubestellar/ui:frontend-dev-$(git rev-parse --short HEAD)
              buildah push quay.io/kubestellar/ui:frontend-dev-latest
              cd ..

              # Build and push backend
              cd backend
              buildah bud -t quay.io/kubestellar/ui:backend-dev-$(git rev-parse --short HEAD) -t quay.io/kubestellar/ui:backend-dev-latest .
              buildah push quay.io/kubestellar/ui:backend-dev-$(git rev-parse --short HEAD)
              buildah push quay.io/kubestellar/ui:backend-dev-latest
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 4Gi
