apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bindingpolicies.control.kubestellar.io
spec:
  group: control.kubestellar.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                downsync:
                  type: array
                  items:
                    type: object
                    properties:
                      resources:
                        type: array
                        items:
                          type: string
                      objectSelectors:
                        type: array
                        items:
                          type: object
                          properties:
                            matchLabels:
                              type: object
                              additionalProperties:
                                type: string
                      apiGroup:
                        type: string
                      createOnly:
                        type: boolean
                      namespaces:
                        type: array
                        items:
                          type: string
                clusterSelectors:
                  type: array
                  items:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                bindingMode:
                  type: string
                  enum: ['Downsync']
  scope: Namespaced
  names:
    plural: bindingpolicies
    singular: bindingpolicy
    kind: BindingPolicy
    shortNames:
      - bp
