services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - kubestellar-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - KUBECONFIG=/root/.kube/config
    network_mode: "host"

  redis:
    image: "redis:latest"
    container_name: "kubestellar-redis"
    ports:
      - "6379:6379"
    network_mode: "host"
  
networks:
  kubestellar-network:
    driver: bridge
