services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jwt_db
      - DATABASE_URL=postgres://postgres:password@localhost:5432/jwt_db?sslmode=disable
      - JWT_SECRET=mysecretkey
    depends_on:
      - postgres
    network_mode: "host"

  postgres:
    image: "postgres:latest"
    container_name: "kubestellar-postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jwt_db
    ports:
      - "5432:5432"
    network_mode: "host"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: "kubestellar-redis"
    ports:
      - "6379:6379"
    network_mode: "host"

volumes:
  postgres-data:
