services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL:-http://localhost:4000}
        - VITE_SKIP_PREREQUISITES_CHECK=${VITE_SKIP_PREREQUISITES_CHECK:-true}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-0.1.0}
    ports:
      - '${FRONTEND_PORT:-5173}:80'
    depends_on:
      - backend
    environment:
      - VITE_SKIP_PREREQUISITES_CHECK=${VITE_SKIP_PREREQUISITES_CHECK:-true}
      - VITE_BASE_URL=${VITE_BASE_URL:-http://localhost:4000}
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:4000}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT:-4000}:4000'
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN:-http://localhost:5173}
    depends_on:
      - redis
    network_mode: 'host'

  redis:
    image: '${REDIS_IMAGE:-ghcr.io/kubestellar/ui/redis:latest}'
    container_name: '${REDIS_CONTAINER_NAME:-kubestellar-redis}'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    network_mode: 'host'