services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - backend
    environment:
      - VITE_SKIP_PREREQUISITES_CHECK=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
      - '4001:4001'
      - '5174:5174'
    volumes:
      - ~/.kube:/root/.kube
      - ./backend/routes:/root/routes  # Mount routes directory to /root/routes
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
    network_mode: 'host'

  redis:
    image: 'redis:latest'
    container_name: 'kubestellar-redis'
    ports:
      - '6379:6379'
    network_mode: 'host'
