services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
    network_mode: "host"


  redis:
    image: "redis:latest"
    container_name: "kubestellar-redis"
    ports:
      - "6379:6379"
    network_mode: "host"

