services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_SKIP_PREREQUISITES_CHECK=true
    networks:
      - kubestellar-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - kubestellar-network

  redis:
    image: "redis:latest"
    container_name: "kubestellar-redis"
    ports:
      - "6379:6379"
    networks:
      - kubestellar-network

networks:
  kubestellar-network:
    driver: bridge

