services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - kubestellar-network

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.kube:/root/.kube
    environment:
      - KUBECONFIG=/root/.kube/config
    network_mode: "host"  # <--- Use host network mode (Linux only)
    # networks:
    #   - kubestellar-network

networks:
  kubestellar-network:
    driver: bridge