apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo-terminal
  name: pod-access-role
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get']
  - apiGroups: ['']
    resources: ['pods/exec']
    verbs: ['create']
