root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o ./bin/main ./main.go"
  bin = "bin/main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = [ "bin"]
  include_dir = []
  exclude_file = []
  delay = 1000
  stop_on_error = true
  log = "air_errors.log"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true 