# PostgreSQL initialization ConfigMap
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  labels:
    app: postgresql
    component: database
data:
  000001_init_schema.up.sql: |
    -- Create users table
    CREATE TABLE IF NOT EXISTS users (
    	id SERIAL PRIMARY KEY,
    	username VARCHAR(255) UNIQUE NOT NULL,
    	password VARCHAR(255) NOT NULL,
    	is_admin BOOLEAN DEFAULT FALSE,
    	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create user_permissions table
    CREATE TABLE IF NOT EXISTS user_permissions (
    	id SERIAL PRIMARY KEY,
    	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    	component VARCHAR(255) NOT NULL,
    	permission VARCHAR(50) NOT NULL CHECK (permission IN ('read', 'write')),
    	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    	UNIQUE(user_id, component)
    );

    -- Create indexes for better performance
    CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
    CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin);
    CREATE INDEX IF NOT EXISTS idx_user_permissions_user_id ON user_permissions(user_id);
    CREATE INDEX IF NOT EXISTS idx_user_permissions_component ON user_permissions(component);
{{- end }}