# This chart was originally developed by @MAVRICK-1
# Source: https://github.com/MAVRICK-1/kubestellar-ui

apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-secret
type: Opaque
data:
  config: {{ .Values.kubeConfig | b64enc | quote }}
