# This chart was originally developed by @MAVRICK-1
# Source: https://github.com/MAVRICK-1/kubestellar-ui

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: {{ .Values.backend.port }}
