# Spellcheck configuration for check-spelling/check-spelling action
# This uses a format compatible with check-spelling action

# Custom wordlist
words:
  - wordlist: .github/spellcheck/.wordlist.txt

# File patterns to check
files:
  - "**/*.md"
  - "**/*.json"

# Exclude patterns
exclude:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".git/**"
  - "coverage/**"
  - "frontend/coverage/**"
  - "backend/test/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/*.wasm"
  - "**/*.gz"
  - "**/*.tar"
  - "**/*.zip"
  - "**/*.lock"
  - "**/package-lock.json"
  - "**/go.sum"
  - "**/yarn.lock"
  - "**/pnpm-lock.yaml"

# Language settings
language: en

