replicaCount: 1

frontend:
  image: mavrick1/kubestellar-f:latest
  port: 80

backend:
  image: mavrick1/kubestellar-b:latest
  port: 4000

redis:
  image: redis:7.0-alpine
  port: 6379
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: false
    size: 1Gi
    storageClass: standard


kubeConfig: ""

# Container/chart image versions, please do not change them unless you know what you are doing.
KUBECTL_VERSION: "1.31.0"
