#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format files with Prettier, excluding Docker files
npx prettier --write --list-different --ignore-path .prettierignore .
# Run linting
npm run lint
# Format Go files with gofmt
echo "Running gofmt on Go files..."
find . -name '*.go' | xargs gofmt -w
