name: Create Version Packages PR

on:
  push:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Changesets
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 👇 Important: still needs working-directory for Changesets action
        working-directory: frontend

