name: "Size Limit"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check bundle size
        id: size-limit
        run: npm run size-limit > size-limit-output.txt

      - name: Post bundle size comment
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            
            try {
              const output = fs.readFileSync('size-limit-output.txt', 'utf8');
              
              // Get the pull request number from the event context
              const prNumber = context.issue.number;
              
              if (!prNumber) {
                console.log('No pull request number found. Skipping comment creation.');
                return;
              }

              const comment = `### 🚦 Size Limit Report
              \`\`\`
              ${output}
              \`\`\``;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: prNumber,
                body: comment
              });
              
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }