name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - "release-*"
    paths:
      - ".github/workflows/spellcheck.yml"
      - ".github/spellcheck/.spellcheck.yml"
      - ".github/spellcheck/.wordlist.txt"
      - "**/*.md"
  pull_request:
    branches:
      - "**"
    paths:
      - "**/*.md"
      - ".github/spellcheck/**"
      - ".github/workflows/spellcheck.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  spellcheck:
    name: Run Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Spellcheck
        uses: check-spelling/check-spelling@prerelease
        with:
          config: .github/spellcheck/.spellcheck.yml

