name: Trivy Vulnerability Scanner

on:
  pull_request:
    paths:
      - '**/package.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '.github/workflows/**'


jobs:
  scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner (log output)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          exit-code: '1' 
          trivy-args: '--no-dev'

      - name: Run Trivy vulnerability scanner (SARIF report)
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          trivy-args: '--no-dev'
          
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
