name: Trivy Vulnerability Scanner

on:
  pull_request:
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '**/.github/workflows/**'

jobs:
  scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner (filesystem scan)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL'
          vuln-type: 'os,library'
          # trivyignores: .trivyignore
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
