name: Trivy Vulnerability Scanner

on:
  pull_request:
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '**/.github/workflows/**'

jobs:
  scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Trivy vulnerability database
        uses: actions/cache@v3
        with:
          path: .trivycache/
          key: ${{ runner.os }}-trivy-${{ hashFiles('**/Dockerfile', '**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-trivy-
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.16.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
